### ISSUE TITLE
Looking for insight into what happened

### ISSUE THREAD

**Issue by enov** [mena-devs/open_letter#10]
Could someone shed some light on what happened exactly, and why JSConfEU does not recommend the Beirut conference anymore?

Thanks

**Comment by Mahmoudz** [comment]
+1

**Comment by Link-** [comment]
Hey guys, we don't know the details and the full story of what happened. However, given that JSConfEU have release a public statement warning speakers and potential attendees from being part of the event and specifically mentioning 'Beirut', we felt compelled to clarify that this incident is in fact isolated. The message is not intended for the JSConfEU organizers, who fully understand the separation, it is intended to the wider audience who saw the tweets and didn't understand what went wrong.

I advise you to have a look at the following links and tweets to gain more insight on how the situation was handled:
https://t.co/SzCf8YaNmk
https://twitter.com/conversionpoint/status/687345321144377344
https://twitter.com/ag_dubs/status/687345432134037504
https://twitter.com/conversionpoint/with_replies

**Comment by enov** [comment]
Looks like there's a public acknowledgement of mistakes:

http://lightningtalks.me/withdrawing-from-jsconf-beirut/

I think that's courageous, and will have a positive impact.

**Comment by constantine-nikolaou** [comment]
@enov +1, thanks for sharing and we totally agree that it is a courageous act.

**Comment by enov** [comment]
I just noticed that the conference is postponed to March 12 – 13, 2016.

**Comment by Link-** [comment]
Other members of the community took it upon themselves to reboot the conf. and push the dates to March.

**Comment by enov** [comment]
Closing this. Thank you @cnicolaou @Link- for your replies :+1:
